version: "3"

services:
  lms_pma:
    image: phpmyadmin/phpmyadmin
    container_name: lms_pmas
    restart: unless-stopped
    environment:
      PMA_HOST: library-db.c96wc2g2czpr.eu-north-1.rds.amazonaws.com
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: Shravan04
      # PMA_ARBITRARY: 1
    ports:
      - 8081:80
volumes:
  dbdata:
